let parklist = [
["Birmingham Civil Rights National Monument", "Alabama"],
["Freedom Riders National Monument", "Alabama"],
["Horseshoe Bend National Military Park", "Alabama"],
["Little River Canyon National Preserve", "Alabama"],
["Russell Cave National Monument", "Alabama"],
["Tuskegee Airmen National Historic Site", "Alabama"],
["Tuskegee Institute National Historic Site", "Alabama"],
["Alagnak Wild River", "Alaska"],
["Aniakchak National Monument", "Alaska"],
["Aniakchak National Preserve", "Alaska"],
["Bering Land Bridge National Preserve", "Alaska"],
["Cape Krusenstern National Monument", "Alaska"],
["Denali National Park", "Alaska"],
["Denali National Preserve", "Alaska"],
["Gates of the Arctic National Park", "Alaska"],
["Gates of the Arctic National Preserve", "Alaska"],
["Glacier Bay National Park", "Alaska"],
["Glacier Bay National Preserve", "Alaska"],
["Katmai National Park", "Alaska"],
["Katmai National Preserve", "Alaska"],
["Kenai Fjords National Park", "Alaska"],
["Klondike Gold Rush National Historical Park", "Alaska"],
["Klondike Gold Rush National Historical Park", "Washington"],
["Kobuk Valley National Park", "Alaska"],
["Lake Clark National Park", "Alaska"],
["Lake Clark National Preserve", "Alaska"],
["Noatak National Preserve", "Alaska"],
["Sitka National Historical Park", "Alaska"],
["Wrangell-St. Elias National Park", "Alaska"],
["Wrangell-St. Elias National Preserve", "Alaska"],
["Yukon-Charley Rivers National Preserve", "Alaska"],
["National Park of American Samoa", "American Samoa"],
["Canyon De Chelly National Monument", "Arizona"],
["Casa Grande Ruins National Monument", "Arizona"],
["Chiricahua National Monument", "Arizona"],
["Coronado National Memorial", "Arizona"],
["Fort Bowie National Historic Site", "Arizona"],
["Glen Canyon National Recreation Area", "Arizona"],
["Glen Canyon National Recreation Area", "Utah"],
["Grand Canyon National Park", "Arizona"],
["Hohokam Pima National Monument", "Arizona"],
["Hubbell Trading Post National Historic Site", "Arizona"],
["Montezuma Castle National Monument", "Arizona"],
["Navajo National Monument", "Arizona"],
["Organ Pipe Cactus National Monument", "Arizona"],
["Petrified Forest National Park", "Arizona"],
["Pipe Spring National Monument", "Arizona"],
["Saguaro National Park", "Arizona"],
["Sunset Crater Volcano National Monument", "Arizona"],
["Tonto National Monument", "Arizona"],
["Tumacacori National Historical Park", "Arizona"],
["Tuzigoot National Monument", "Arizona"],
["Walnut Canyon National Monument", "Arizona"],
["Wupatki National Monument", "Arizona"],
["Arkansas Post National Memorial", "Arkansas"],
["Buffalo National River", "Arkansas"],
["Fort Smith National Historic Site", "Arkansas"],
["Hot Springs National Park", "Arkansas"],
["Little Rock Central High School National Historic Site", "Arkansas"],
["Pea Ridge National Military Park", "Arkansas"],
["President William Jefferson Clinton Birthplace Home National Historic Site", "Arkansas"],
["Cabrillo National Monument", "California"],
["Castle Mountains National Monument", "California"],
["César E. Chávez National Monument", "California"],
["Channel Islands National Park", "California"],
["Death Valley National Park", "California"],
["Death Valley National Park", "Nevada"],
["Devils Postpile National Monument", "California"],
["Eugene O'Neill National Historic Site", "California"],
["Fort Point National Historic Site", "California"],
["Golden Gate National Recreation Area", "California"],
["John Muir National Historic Site", "California"],
["Joshua Tree National Park", "California"],
["Kings Canyon National Park", "California"],
["Lassen Volcanic National Park", "California"],
["Lava Beds National Monument", "California"],
["Manzanar National Historic Site", "California"],
["Mojave National Preserve", "California"],
["Muir Woods National Monument", "California"],
["Pinnacles National Park", "California"],
["Point Reyes National Seashore", "California"],
["Port Chicago Naval Magazine National Memorial", "California"],
["Redwood National Park", "California"],
["Rosie the Riveter World War II Home Front National Historical Park", "California"],
["San Francisco Maritime National Historical Park", "California"],
["Santa Monica Mountains National Recreation Area", "California"],
["Sequoia National Park", "California"],
["Tule Lake National Monument", "California"],
["Whiskeytown-Shasta-Trinity National Recreation Area", "California"],
["Yosemite National Park", "California"],
["Bent's Old Fort National Historic Site", "Colorado"],
["Black Canyon of the Gunnison National Park", "Colorado"],
["Colorado National Monument", "Colorado"],
["Curecanti National Recreation Area", "Colorado"],
["Dinosaur National Monument", "Colorado"],
["Dinosaur National Monument", "Utah"],
["Florissant Fossil Beds National Monument", "Colorado"],
["Great Sand Dunes National Park", "Colorado"],
["Great Sand Dunes National Preserve", "Colorado"],
["Hovenweep National Monument", "Colorado"],
["Hovenweep National Monument", "Utah"],
["Mesa Verde National Park", "Colorado"],
["Rocky Mountain National Park", "Colorado"],
["Sand Creek Massacre National Historic Site", "Colorado"],
["Yucca House National Monument", "Colorado"],
["Weir Farm National Historical Park", "Connecticut"],
["First State National Historical Park", "Delaware"],
["First State National Historical Park", "Pennsylvania"],
["Big Cypress National Preserve", "Florida"],
["Biscayne National Park", "Florida"],
["Canaveral National Seashore", "Florida"],
["Castillo de San Marcos National Monument", "Florida"],
["De Soto National Memorial", "Florida"],
["Dry Tortugas National Park", "Florida"],
["Everglades National Park", "Florida"],
["Fort Caroline National Memorial", "Florida"],
["Fort Matanzas National Monument", "Florida"],
["Gulf Islands National Seashore", "Florida"],
["Gulf Islands National Seashore", "Mississippi"],
["Timucuan Ecological and Historic Preserve", "Florida"],
["Andersonville National Historic Site", "Georgia"],
["Chattahoochee River National Recreation Area", "Georgia"],
["Chickamauga & Chattanooga National Military Park", "Georgia"],
["Chickamauga & Chattanooga National Military Park", "Tennessee"],
["Cumberland Island National Seashore", "Georgia"],
["Fort Frederica National Monument", "Georgia"],
["Fort Pulaski National Monument", "Georgia"],
["Jimmy Carter National Historical Park", "Georgia"],
["Kennesaw Mountain National Battlefield Park", "Georgia"],
["Martin Luther King Jr. National Historical Park", "Georgia"],
["Ocmulgee Mounds National Historical Park", "Georgia"],
["War in the Pacific National Historical Park", "Guam"],
["Haleakala National Park", "Hawaii"],
["Hawaii Volcanoes National Park", "Hawaii"],
["Honouliuli National Historic Site", "Hawaii"],
["Kalaupapa National Historical Park", "Hawaii"],
["Kaloko-Honokohau National Historical Park", "Hawaii"],
["Pearl Harbor National Memorial", "Hawaii"],
["Pu'uhonua O Honaunau National Historical Park", "Hawaii"],
["Pu'ukohola Heiau National Historic Site", "Hawaii"],
["City of Rocks National Reserve", "Idaho"],
["Craters of the Moon National Monument", "Idaho"],
["Craters of the Moon National Preserve", "Idaho"],
["Hagerman Fossil Beds National Monument", "Idaho"],
["Minidoka National Historic Site", "Idaho"],
["Nez Perce National Historical Park", "Idaho"],
["Lincoln Home National Historic Site", "Illinois"],
["New Philadelphia National Historic Site", "Illinois"],
["Pullman National Historical Park", "Illinois"],
["George Rogers Clark National Historical Park", "Indiana"],
["Indiana Dunes National Park", "Indiana"],
["Lincoln Boyhood National Memorial", "Indiana"],
["Effigy Mounds National Monument", "Iowa"],
["Herbert Hoover National Historic Site", "Iowa"],
["Brown v. Board of Education National Historical Park", "Kansas"],
["Fort Larned National Historic Site", "Kansas"],
["Fort Scott National Historic Site", "Kansas"],
["Nicodemus National Historic Site", "Kansas"],
["Tallgrass Prairie National Preserve", "Kansas"],
["Abraham Lincoln Birthplace National Historical Park", "Kentucky"],
["Camp Nelson National Monument", "Kentucky"],
["Cumberland Gap National Historical Park", "Kentucky"],
["Cumberland Gap National Historical Park", "Tennessee"],
["Cumberland Gap National Historical Park", "Virginia"],
["Mammoth Cave National Park", "Kentucky"],
["Mill Springs Battlefield National Monument", "Kentucky"],
["Cane River Creole National Historical Park", "Louisiana"],
["Jean Lafitte National Historical Park and Preserve", "Louisiana"],
["New Orleans Jazz National Historical Park", "Louisiana"],
["Poverty Point National Monument", "Louisiana"],
["Acadia National Park", "Maine"],
["Appalachian National Scenic Trail", "Maine"],
["Appalachian National Scenic Trail", "New Hampshire"],
["Appalachian National Scenic Trail", "Vermont"],
["Appalachian National Scenic Trail", "Massachusetts"],
["Appalachian National Scenic Trail", "Connecticut"],
["Appalachian National Scenic Trail", "New York"],
["Appalachian National Scenic Trail", "New Jersey"],
["Appalachian National Scenic Trail", "Pennsylvania"],
["Appalachian National Scenic Trail", "Maryland"],
["Appalachian National Scenic Trail", "West Virginia"],
["Appalachian National Scenic Trail", "Virginia"],
["Appalachian National Scenic Trail", "Tennessee"],
["Appalachian National Scenic Trail", "North Carolina"],
["Appalachian National Scenic Trail", "Georgia"],
["Katahdin Woods and Waters National Monument", "Maine"],
["Saint Croix Island International Historic Site", "Maine"],
["Antietam National Battlefield", "Maryland"],
["Assateague Island National Seashore", "Maryland"],
["Assateague Island National Seashore", "Virginia"],
["Catoctin Mountain Park", "Maryland"],
["Chesapeake and Ohio Canal National Historical Park", "Maryland"],
["Chesapeake and Ohio Canal National Historical Park", "Washington DC"],
["Clara Barton National Historic Site", "Maryland"],
["Fort McHenry National Monument and Historic Shrine", "Maryland"],
["Fort Washington Park", "Maryland"],
["Greenbelt Park", "Maryland"],
["Hampton National Historic Site", "Maryland"],
["Harriet Tubman Underground Railroad National Historical Park", "Maryland"],
["Monocacy National Battlefield", "Maryland"],
["Piscataway Park", "Maryland"],
["Potomac Heritage National Scenic Trail", "Maryland"],
["Potomac Heritage National Scenic Trail", "Pennsylvania"],
["Potomac Heritage National Scenic Trail", "Virginia"],
["Potomac Heritage National Scenic Trail", "Washington DC"],
["Thomas Stone National Historic Site", "Maryland"],
["Adams National Historical Park", "Massachusetts"],
["Boston African American National Historic Site", "Massachusetts"],
["Boston Harbor Islands National Recreation Area", "Massachusetts"],
["Boston National Historical Park", "Massachusetts"],
["Cape Cod National Seashore", "Massachusetts"],
["Frederick Law Olmsted National Historic Site", "Massachusetts"],
["John F. Kennedy National Historic Site", "Massachusetts"],
["Longfellow House–Washington's Headquarters National Historic Site", "Massachusetts"],
["Lowell National Historical Park", "Massachusetts"],
["Minute Man National Historical Park", "Massachusetts"],
["New Bedford Whaling National Historical Park", "Massachusetts"],
["Salem Maritime National Historic Site", "Massachusetts"],
["Saugus Iron Works National Historic Site", "Massachusetts"],
["Springfield Armory National Historic Site", "Massachusetts"],
["Isle Royale National Park", "Michigan"],
["Keweenaw National Historical Park", "Michigan"],
["Pictured Rocks National Lakeshore", "Michigan"],
["River Raisin National Battlefield Park", "Michigan"],
["Sleeping Bear Dunes National Lakeshore", "Michigan"],
["Grand Portage National Monument", "Minnesota"],
["Mississippi National River and Recreation Area", "Minnesota"],
["Pipestone National Monument", "Minnesota"],
["Voyageurs National Park", "Minnesota"],
["Brices Cross Roads National Battlefield Site", "Mississippi"],
["Medgar and Myrlie Evers Home National Monument", "Mississippi"],
["Natchez National Historical Park", "Mississippi"],
["Natchez Trace Parkway", "Mississippi"],
["Natchez Trace Parkway", "Alabama"],
["Natchez Trace Parkway", "Tennessee"],
["Natchez Trace National Scenic Trail", "Mississippi"],
["Natchez Trace National Scenic Trail", "Alabama"],
["Natchez Trace National Scenic Trail", "Tennessee"],
["Tupelo National Battlefield", "Mississippi"],
["Vicksburg National Military Park", "Mississippi"],
["Vicksburg National Military Park", "Louisiana"],
["Gateway Arch National Park", "Missouri"],
["George Washington Carver National Monument", "Missouri"],
["Harry S Truman National Historic Site", "Missouri"],
["Ozark National Scenic Riverways", "Missouri"],
["Ste. Genevieve National Historical Park", "Missouri"],
["Ulysses S. Grant National Historic Site", "Missouri"],
["Wilson's Creek National Battlefield", "Missouri"],
["Big Hole National Battlefield", "Montana"],
["Bighorn Canyon National Recreation Area", "Montana"],
["Glacier National Park", "Montana"],
["Grant-Kohrs Ranch National Historic Site", "Montana"],
["Little Bighorn Battlefield National Monument", "Montana"],
["Agate Fossil Beds National Monument", "Nebraska"],
["Homestead National Historical Park", "Nebraska"],
["Missouri National Recreational River", "Nebraska"],
["Missouri National Recreational River", "South Dakota"],
["Niobrara National Scenic River", "Nebraska"],
["Scotts Bluff National Monument", "Nebraska"],
["Great Basin National Park", "Nevada"],
["Lake Mead National Recreation Area", "Nevada"],
["Lake Mead National Recreation Area", "Arizona"],
["Tule Springs Fossil Beds National Monument", "Nevada"],
["Saint-Gaudens National Historical Park", "New Hampshire"],
["Delaware Water Gap National Recreation Area", "New Jersey"],
["Delaware Water Gap National Recreation Area", "Pennsylvania"],
["Great Egg Harbor Scenic and Recreational River", "New Jersey"],
["Morristown National Historical Park", "New Jersey"],
["Paterson Great Falls National Historical Park", "New Jersey"],
["Thomas Edison National Historical Park", "New Jersey"],
["Aztec Ruins National Monument", "New Mexico"],
["Bandelier National Monument", "New Mexico"],
["Capulin Volcano National Monument", "New Mexico"],
["Carlsbad Caverns National Park", "New Mexico"],
["Chaco Culture National Historical Park", "New Mexico"],
["El Malpais National Monument", "New Mexico"],
["El Morro National Monument", "New Mexico"],
["Fort Union National Monument", "New Mexico"],
["Gila Cliff Dwellings National Monument", "New Mexico"],
["Manhattan Project National Historical Park", "New Mexico"],
["Manhattan Project National Historical Park", "Tennessee"],
["Manhattan Project National Historical Park", "Washington"],
["Pecos National Historical Park", "New Mexico"],
["Petroglyph National Monument", "New Mexico"],
["Salinas Pueblo Missions National Monument", "New Mexico"],
["Valles Caldera National Preserve", "New Mexico"],
["White Sands National Park", "New Mexico"],
["African Burial Ground National Monument", "New York"],
["Castle Clinton National Monument", "New York"],
["Eleanor Roosevelt National Historic Site", "New York"],
["Federal Hall National Memorial", "New York"],
["Fire Island National Seashore", "New York"],
["Fort Stanwix National Monument", "New York"],
["Gateway National Recreation Area", "New York"],
["Gateway National Recreation Area", "New Jersey"],
["General Grant National Memorial", "New York"],
["Governors Island National Monument", "New York"],
["Hamilton Grange National Memorial", "New York"],
["Harriet Tubman National Historical Park", "New York"],
["Home of Franklin D. Roosevelt National Historic Site", "New York"],
["Martin Van Buren National Historic Site", "New York"],
["Saint Paul's Church National Historic Site", "New York"],
["Sagamore Hill National Historic Site", "New York"],
["Saratoga National Historical Park", "New York"],
["Statue of Liberty National Monument", "New York"],
["Statue of Liberty National Monument", "New Jersey"],
["Stonewall National Monument", "New York"],
["Theodore Roosevelt Birthplace National Historic Site", "New York"],
["Theodore Roosevelt Inaugural National Historic Site", "New York"],
["Vanderbilt Mansion National Historic Site", "New York"],
["Women's Rights National Historical Park", "New York"],
["Blue Ridge Parkway", "North Carolina"],
["Blue Ridge Parkway", "Virginia"],
["Cape Hatteras National Seashore", "North Carolina"],
["Cape Lookout National Seashore", "North Carolina"],
["Carl Sandburg Home National Historic Site", "North Carolina"],
["Fort Raleigh National Historic Site", "North Carolina"],
["Guilford Courthouse National Military Park", "North Carolina"],
["Moores Creek National Battlefield", "North Carolina"],
["Wright Brothers National Memorial", "North Carolina"],
["Fort Union Trading Post National Historic Site", "North Dakota"],
["Fort Union Trading Post National Historic Site", "Montana"],
["Knife River Indian Villages National Historic Site", "North Dakota"],
["Theodore Roosevelt National Park", "North Dakota"],
["Charles Young Buffalo Soldiers National Monument", "Ohio"],
["Cuyahoga Valley National Park", "Ohio"],
["Dayton Aviation Heritage National Historical Park", "Ohio"],
["First Ladies National Historic Site", "Ohio"],
["Hopewell Culture National Historical Park", "Ohio"],
["James A. Garfield National Historic Site", "Ohio"],
["Perry's Victory and International Peace Memorial", "Ohio"],
["William Howard Taft National Historic Site", "Ohio"],
["Chickasaw National Recreation Area", "Oklahoma"],
["Washita Battlefield National Historic Site", "Oklahoma"],
["Crater Lake National Park", "Oregon"],
["Lewis and Clark National Historical Park", "Oregon"],
["Lewis and Clark National Historical Park", "Washington"],
["John Day Fossil Beds National Monument", "Oregon"],
["Oregon Caves National Monument and Preserve", "Oregon"],
["Allegheny Portage Railroad National Historic Site", "Pennsylvania"],
["Edgar Allan Poe National Historic Site", "Pennsylvania"],
["Eisenhower National Historic Site", "Pennsylvania"],
["Flight 93 National Memorial", "Pennsylvania"],
["Fort Necessity National Battlefield", "Pennsylvania"],
["Friendship Hill National Historic Site", "Pennsylvania"],
["Gettysburg National Military Park", "Pennsylvania"],
["Hopewell Furnace National Historic Site", "Pennsylvania"],
["Independence National Historical Park", "Pennsylvania"],
["Johnstown Flood National Memorial", "Pennsylvania"],
["Middle Delaware National Scenic River", "Pennsylvania"],
["Steamtown National Historic Site", "Pennsylvania"],
["Thaddeus Kosciuszko National Memorial", "Pennsylvania"],
["Upper Delaware Scenic and Recreational River", "Pennsylvania"],
["Valley Forge National Historical Park", "Pennsylvania"],
["San Juan National Historic Site", "Puerto Rico"],
["Blackstone River Valley National Historical Park", "Rhode Island"],
["Blackstone River Valley National Historical Park", "Massachusetts"],
["Roger Williams National Memorial", "Rhode Island"],
["Charles Pinckney National Historic Site", "South Carolina"],
["Congaree National Park", "South Carolina"],
["Cowpens National Battlefield", "South Carolina"],
["Fort Sumter and Fort Moultrie National Historical Park", "South Carolina"],
["Kings Mountain National Military Park", "South Carolina"],
["Ninety Six National Historic Site", "South Carolina"],
["Reconstruction Era National Historical Park", "South Carolina"],
["Badlands National Park", "South Dakota"],
["Jewel Cave National Monument", "South Dakota"],
["Minuteman Missile National Historic Site", "South Dakota"],
["Mount Rushmore National Memorial", "South Dakota"],
["Wind Cave National Park", "South Dakota"],
["Andrew Johnson National Historic Site", "Tennessee"],
["Big South Fork National River and Recreation Area", "Tennessee"],
["Big South Fork National River and Recreation Area", "Kentucky"],
["Fort Donelson National Battlefield", "Tennessee"],
["Fort Donelson National Battlefield", "Kentucky"],
["Great Smoky Mountains National Park", "Tennessee"],
["Great Smoky Mountains National Park", "North Carolina"],
["Obed Wild and Scenic River", "Tennessee"],
["Shiloh National Military Park", "Tennessee"],
["Shiloh National Military Park", "Mississippi"],
["Stones River National Battlefield", "Tennessee"],
["Alibates Flint Quarries National Monument", "Texas"],
["Amistad National Recreation Area", "Texas"],
["Big Bend National Park", "Texas"],
["Big Thicket National Preserve", "Texas"],
["Chamizal National Memorial", "Texas"],
["Fort Davis National Historic Site", "Texas"],
["Guadalupe Mountains National Park", "Texas"],
["Lake Meredith National Recreation Area", "Texas"],
["Lyndon B. Johnson National Historical Park", "Texas"],
["Padre Island National Seashore", "Texas"],
["Palo Alto Battlefield National Historical Park", "Texas"],
["Rio Grande Wild and Scenic River", "Texas"],
["San Antonio Missions National Historical Park", "Texas"],
["Waco Mammoth National Monument", "Texas"],
["Arches National Park", "Utah"],
["Bryce Canyon National Park", "Utah"],
["Canyonlands National Park", "Utah"],
["Capitol Reef National Park", "Utah"],
["Cedar Breaks National Monument", "Utah"],
["Golden Spike National Historical Park", "Utah"],
["Natural Bridges National Monument", "Utah"],
["Rainbow Bridge National Monument", "Utah"],
["Timpanogos Cave National Monument", "Utah"],
["Zion National Park", "Utah"],
["Marsh-Billings-Rockefeller National Historical Park", "Vermont"],
["Buck Island Reef National Monument", "Virgin Islands"],
["Christiansted National Historic Site", "Virgin Islands"],
["Salt River Bay National Historical Park and Ecological Preserve", "Virgin Islands"],
["Virgin Islands National Park", "Virgin Islands"],
["Virgin Islands Coral Reef National Monument", "Virgin Islands"],
["Appomattox Court House National Historical Park", "Virginia"],
["Arlington House, The Robert E. Lee Memorial", "Virginia"],
["Booker T. Washington National Monument", "Virginia"],
["Cedar Creek and Belle Grove National Historical Park", "Virginia"],
["Colonial National Historical Park", "Virginia"],
["Fort Monroe National Monument", "Virginia"],
["Fredericksburg and Spotsylvania National Military Park", "Virginia"],
["George Washington Birthplace National Monument", "Virginia"],
["George Washington Memorial Parkway", "Virginia"],
["George Washington Memorial Parkway", "Maryland"],
["George Washington Memorial Parkway", "Washington DC"],
["Maggie L. Walker National Historic Site", "Virginia"],
["Manassas National Battlefield Park", "Virginia"],
["Petersburg National Battlefield", "Virginia"],
["Prince William Forest Park", "Virginia"],
["Richmond National Battlefield Park", "Virginia"],
["Shenandoah National Park", "Virginia"],
["Wolf Trap National Park for the Performing Arts", "Virginia"],
["Ebey's Landing National Historical Reserve", "Washington"],
["Fort Vancouver National Historic Site", "Washington"],
["Fort Vancouver National Historic Site", "Oregon"],
["Lake Chelan National Recreation Area", "Washington"],
["Lake Roosevelt National Recreation Area", "Washington"],
["Mount Rainier National Park", "Washington"],
["North Cascades National Park", "Washington"],
["Olympic National Park", "Washington"],
["Ross Lake National Recreation Area", "Washington"],
["San Juan Island National Historical Park", "Washington"],
["Whitman Mission National Historic Site", "Washington"],
["Belmont-Paul Women's Equality National Monument", "Washington DC"],
["Carter G. Woodson Home National Historic Site", "Washington DC"],
["Constitution Gardens", "Washington DC"],
["Dwight D. Eisenhower Memorial", "Washington DC"],
["Ford's Theatre National Historic Site", "Washington DC"],
["Franklin D. Roosevelt Memorial", "Washington DC"],
["Frederick Douglass National Historic Site", "Washington DC"],
["Korean War Veterans Memorial", "Washington DC"],
["Lincoln Memorial", "Washington DC"],
["Lyndon Baines Johnson Memorial Grove on the Potomac", "Washington DC"],
["Martin Luther King, Jr. Memorial", "Washington DC"],
["Mary McLeod Bethune Council House National Historic Site", "Washington DC"],
["National Capital Parks-East", "Washington DC"],
["National Mall and Memorial Parks", "Washington DC"],
["Pennsylvania Avenue National Historic Site", "Washington DC"],
["Rock Creek Park", "Washington DC"],
["Theodore Roosevelt Island", "Washington DC"],
["Thomas Jefferson Memorial", "Washington DC"],
["Vietnam Veterans Memorial", "Washington DC"],
["Washington Monument", "Washington DC"],
["White House and President's Park", "Washington DC"],
["World War I Memorial", "Washington DC"],
["World War II Memorial", "Washington DC"],
["Bluestone National Scenic River", "West Virginia"],
["Gauley River National Recreation Area", "West Virginia"],
["Harpers Ferry National Historical Park", "West Virginia"],
["New River Gorge National Park and Preserve", "West Virginia"],
["Apostle Islands National Lakeshore", "Wisconsin"],
["Saint Croix National Scenic Riverway", "Wisconsin"],
["Saint Croix National Scenic Riverway", "Minnesota"],
["Devils Tower National Monument", "Wyoming"],
["Fort Laramie National Historic Site", "Wyoming"],
["Fossil Butte National Monument", "Wyoming"],
["Grand Teton National Park", "Wyoming"],
["John D. Rockefeller Jr. Memorial Parkway", "Wyoming"],
["Yellowstone National Park", "Wyoming"],
["Yellowstone National Park", "Idaho"],
["Yellowstone National Park", "Montana"]
];



const totalparklist = [];
for(var i = 0; i < parklist.length; i++) {
	totalparklist[i] =  parklist[i][0];
}

let uniqueparklist = totalparklist.filter((element, index) => {
    return totalparklist.indexOf(element) === index;
});

uniqueparklist.sort();







const totalstatelist = [];
for(var i = 0; i < parklist.length; i++) {
	totalstatelist[i] =  parklist[i][1];
}

let uniquestatelist = totalstatelist.filter((element, index) => {
    return totalstatelist.indexOf(element) === index;
});

uniquestatelist.sort();





